// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FitbitToken struct {
	// Api version:
	Api         string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	AccessToken string `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	// TokenType is the type of token.
	// The Type method returns either this or "Bearer", the default.
	TokenType string `protobuf:"bytes,3,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	// RefreshToken is a token that's used by the application
	// (as opposed to the user) to refresh the access token
	// if it expires.
	RefreshToken string `protobuf:"bytes,4,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	// Expiry is the optional expiration time of the access token.
	//
	// If zero, TokenSource implementations will reuse the same
	// token forever and RefreshToken or equivalent
	// mechanisms for that TokenSource will not be used.
	Expiry               string   `protobuf:"bytes,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	UserId               string   `protobuf:"bytes,6,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FitbitToken) Reset()         { *m = FitbitToken{} }
func (m *FitbitToken) String() string { return proto.CompactTextString(m) }
func (*FitbitToken) ProtoMessage()    {}
func (*FitbitToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{0}
}

func (m *FitbitToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FitbitToken.Unmarshal(m, b)
}
func (m *FitbitToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FitbitToken.Marshal(b, m, deterministic)
}
func (m *FitbitToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FitbitToken.Merge(m, src)
}
func (m *FitbitToken) XXX_Size() int {
	return xxx_messageInfo_FitbitToken.Size(m)
}
func (m *FitbitToken) XXX_DiscardUnknown() {
	xxx_messageInfo_FitbitToken.DiscardUnknown(m)
}

var xxx_messageInfo_FitbitToken proto.InternalMessageInfo

func (m *FitbitToken) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *FitbitToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *FitbitToken) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *FitbitToken) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *FitbitToken) GetExpiry() string {
	if m != nil {
		return m.Expiry
	}
	return ""
}

func (m *FitbitToken) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// Refresh Token message
type RefreshTokenRequest struct {
	// Api version:
	Api                  string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Item                 string       `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	FitbitToken          *FitbitToken `protobuf:"bytes,3,opt,name=fitbitToken,proto3" json:"fitbitToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RefreshTokenRequest) Reset()         { *m = RefreshTokenRequest{} }
func (m *RefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRequest) ProtoMessage()    {}
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{1}
}

func (m *RefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRequest.Unmarshal(m, b)
}
func (m *RefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRequest.Merge(m, src)
}
func (m *RefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRequest.Size(m)
}
func (m *RefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRequest proto.InternalMessageInfo

func (m *RefreshTokenRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *RefreshTokenRequest) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *RefreshTokenRequest) GetFitbitToken() *FitbitToken {
	if m != nil {
		return m.FitbitToken
	}
	return nil
}

type RefreshTokenResponse struct {
	// Api version:
	Api                  string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Item                 string       `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	FitbitTokenNew       *FitbitToken `protobuf:"bytes,3,opt,name=fitbitTokenNew,proto3" json:"fitbitTokenNew,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RefreshTokenResponse) Reset()         { *m = RefreshTokenResponse{} }
func (m *RefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenResponse) ProtoMessage()    {}
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{2}
}

func (m *RefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenResponse.Unmarshal(m, b)
}
func (m *RefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenResponse.Merge(m, src)
}
func (m *RefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenResponse.Size(m)
}
func (m *RefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenResponse proto.InternalMessageInfo

func (m *RefreshTokenResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *RefreshTokenResponse) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *RefreshTokenResponse) GetFitbitTokenNew() *FitbitToken {
	if m != nil {
		return m.FitbitTokenNew
	}
	return nil
}

// Activities Step message
type ActivitiesStep struct {
	DateTime             string   `protobuf:"bytes,1,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	Steps                string   `protobuf:"bytes,2,opt,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivitiesStep) Reset()         { *m = ActivitiesStep{} }
func (m *ActivitiesStep) String() string { return proto.CompactTextString(m) }
func (*ActivitiesStep) ProtoMessage()    {}
func (*ActivitiesStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{3}
}

func (m *ActivitiesStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivitiesStep.Unmarshal(m, b)
}
func (m *ActivitiesStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivitiesStep.Marshal(b, m, deterministic)
}
func (m *ActivitiesStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivitiesStep.Merge(m, src)
}
func (m *ActivitiesStep) XXX_Size() int {
	return xxx_messageInfo_ActivitiesStep.Size(m)
}
func (m *ActivitiesStep) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivitiesStep.DiscardUnknown(m)
}

var xxx_messageInfo_ActivitiesStep proto.InternalMessageInfo

func (m *ActivitiesStep) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func (m *ActivitiesStep) GetSteps() string {
	if m != nil {
		return m.Steps
	}
	return ""
}

type ActivitiesStepRequest struct {
	// Api version:
	Api                  string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Item                 string       `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	FitbitToken          *FitbitToken `protobuf:"bytes,3,opt,name=fitbitToken,proto3" json:"fitbitToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ActivitiesStepRequest) Reset()         { *m = ActivitiesStepRequest{} }
func (m *ActivitiesStepRequest) String() string { return proto.CompactTextString(m) }
func (*ActivitiesStepRequest) ProtoMessage()    {}
func (*ActivitiesStepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{4}
}

func (m *ActivitiesStepRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivitiesStepRequest.Unmarshal(m, b)
}
func (m *ActivitiesStepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivitiesStepRequest.Marshal(b, m, deterministic)
}
func (m *ActivitiesStepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivitiesStepRequest.Merge(m, src)
}
func (m *ActivitiesStepRequest) XXX_Size() int {
	return xxx_messageInfo_ActivitiesStepRequest.Size(m)
}
func (m *ActivitiesStepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivitiesStepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivitiesStepRequest proto.InternalMessageInfo

func (m *ActivitiesStepRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ActivitiesStepRequest) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *ActivitiesStepRequest) GetFitbitToken() *FitbitToken {
	if m != nil {
		return m.FitbitToken
	}
	return nil
}

// Contains list of all ActivitiesStep tasks
type ActivitiesStepResponse struct {
	// Api version:
	Api  string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Item string `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	// List of all ActivitiesStep tasks
	ActivitiesSteps      []*ActivitiesStep `protobuf:"bytes,3,rep,name=activitiesSteps,proto3" json:"activitiesSteps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ActivitiesStepResponse) Reset()         { *m = ActivitiesStepResponse{} }
func (m *ActivitiesStepResponse) String() string { return proto.CompactTextString(m) }
func (*ActivitiesStepResponse) ProtoMessage()    {}
func (*ActivitiesStepResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{5}
}

func (m *ActivitiesStepResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivitiesStepResponse.Unmarshal(m, b)
}
func (m *ActivitiesStepResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivitiesStepResponse.Marshal(b, m, deterministic)
}
func (m *ActivitiesStepResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivitiesStepResponse.Merge(m, src)
}
func (m *ActivitiesStepResponse) XXX_Size() int {
	return xxx_messageInfo_ActivitiesStepResponse.Size(m)
}
func (m *ActivitiesStepResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivitiesStepResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivitiesStepResponse proto.InternalMessageInfo

func (m *ActivitiesStepResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ActivitiesStepResponse) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *ActivitiesStepResponse) GetActivitiesSteps() []*ActivitiesStep {
	if m != nil {
		return m.ActivitiesSteps
	}
	return nil
}

type ActivitiesDistance struct {
	DateTime             string   `protobuf:"bytes,1,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	Distance             string   `protobuf:"bytes,2,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivitiesDistance) Reset()         { *m = ActivitiesDistance{} }
func (m *ActivitiesDistance) String() string { return proto.CompactTextString(m) }
func (*ActivitiesDistance) ProtoMessage()    {}
func (*ActivitiesDistance) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{6}
}

func (m *ActivitiesDistance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivitiesDistance.Unmarshal(m, b)
}
func (m *ActivitiesDistance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivitiesDistance.Marshal(b, m, deterministic)
}
func (m *ActivitiesDistance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivitiesDistance.Merge(m, src)
}
func (m *ActivitiesDistance) XXX_Size() int {
	return xxx_messageInfo_ActivitiesDistance.Size(m)
}
func (m *ActivitiesDistance) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivitiesDistance.DiscardUnknown(m)
}

var xxx_messageInfo_ActivitiesDistance proto.InternalMessageInfo

func (m *ActivitiesDistance) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func (m *ActivitiesDistance) GetDistance() string {
	if m != nil {
		return m.Distance
	}
	return ""
}

type ActivitiesDistanceRequest struct {
	// Api version:
	Api                  string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Item                 string       `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	FitbitToken          *FitbitToken `protobuf:"bytes,3,opt,name=fitbitToken,proto3" json:"fitbitToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ActivitiesDistanceRequest) Reset()         { *m = ActivitiesDistanceRequest{} }
func (m *ActivitiesDistanceRequest) String() string { return proto.CompactTextString(m) }
func (*ActivitiesDistanceRequest) ProtoMessage()    {}
func (*ActivitiesDistanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{7}
}

func (m *ActivitiesDistanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivitiesDistanceRequest.Unmarshal(m, b)
}
func (m *ActivitiesDistanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivitiesDistanceRequest.Marshal(b, m, deterministic)
}
func (m *ActivitiesDistanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivitiesDistanceRequest.Merge(m, src)
}
func (m *ActivitiesDistanceRequest) XXX_Size() int {
	return xxx_messageInfo_ActivitiesDistanceRequest.Size(m)
}
func (m *ActivitiesDistanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivitiesDistanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivitiesDistanceRequest proto.InternalMessageInfo

func (m *ActivitiesDistanceRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ActivitiesDistanceRequest) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *ActivitiesDistanceRequest) GetFitbitToken() *FitbitToken {
	if m != nil {
		return m.FitbitToken
	}
	return nil
}

// Contains list of all Activities Distance tasks
type ActivitiesDistanceResponse struct {
	// Api version:
	Api  string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Item string `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	// List of all ActivitiesStep tasks
	ActivitiesDistance   []*ActivitiesDistance `protobuf:"bytes,3,rep,name=activitiesDistance,proto3" json:"activitiesDistance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ActivitiesDistanceResponse) Reset()         { *m = ActivitiesDistanceResponse{} }
func (m *ActivitiesDistanceResponse) String() string { return proto.CompactTextString(m) }
func (*ActivitiesDistanceResponse) ProtoMessage()    {}
func (*ActivitiesDistanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{8}
}

func (m *ActivitiesDistanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivitiesDistanceResponse.Unmarshal(m, b)
}
func (m *ActivitiesDistanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivitiesDistanceResponse.Marshal(b, m, deterministic)
}
func (m *ActivitiesDistanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivitiesDistanceResponse.Merge(m, src)
}
func (m *ActivitiesDistanceResponse) XXX_Size() int {
	return xxx_messageInfo_ActivitiesDistanceResponse.Size(m)
}
func (m *ActivitiesDistanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivitiesDistanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivitiesDistanceResponse proto.InternalMessageInfo

func (m *ActivitiesDistanceResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ActivitiesDistanceResponse) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *ActivitiesDistanceResponse) GetActivitiesDistance() []*ActivitiesDistance {
	if m != nil {
		return m.ActivitiesDistance
	}
	return nil
}

// HEART RATE
type ActivitiesHeartRate struct {
	DateTime             string   `protobuf:"bytes,1,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	Bead                 string   `protobuf:"bytes,2,opt,name=bead,proto3" json:"bead,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivitiesHeartRate) Reset()         { *m = ActivitiesHeartRate{} }
func (m *ActivitiesHeartRate) String() string { return proto.CompactTextString(m) }
func (*ActivitiesHeartRate) ProtoMessage()    {}
func (*ActivitiesHeartRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{9}
}

func (m *ActivitiesHeartRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivitiesHeartRate.Unmarshal(m, b)
}
func (m *ActivitiesHeartRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivitiesHeartRate.Marshal(b, m, deterministic)
}
func (m *ActivitiesHeartRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivitiesHeartRate.Merge(m, src)
}
func (m *ActivitiesHeartRate) XXX_Size() int {
	return xxx_messageInfo_ActivitiesHeartRate.Size(m)
}
func (m *ActivitiesHeartRate) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivitiesHeartRate.DiscardUnknown(m)
}

var xxx_messageInfo_ActivitiesHeartRate proto.InternalMessageInfo

func (m *ActivitiesHeartRate) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func (m *ActivitiesHeartRate) GetBead() string {
	if m != nil {
		return m.Bead
	}
	return ""
}

type ActivitiesHeartRateRequest struct {
	// Api version:
	Api                  string       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Item                 string       `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	FitbitToken          *FitbitToken `protobuf:"bytes,3,opt,name=fitbitToken,proto3" json:"fitbitToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ActivitiesHeartRateRequest) Reset()         { *m = ActivitiesHeartRateRequest{} }
func (m *ActivitiesHeartRateRequest) String() string { return proto.CompactTextString(m) }
func (*ActivitiesHeartRateRequest) ProtoMessage()    {}
func (*ActivitiesHeartRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{10}
}

func (m *ActivitiesHeartRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivitiesHeartRateRequest.Unmarshal(m, b)
}
func (m *ActivitiesHeartRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivitiesHeartRateRequest.Marshal(b, m, deterministic)
}
func (m *ActivitiesHeartRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivitiesHeartRateRequest.Merge(m, src)
}
func (m *ActivitiesHeartRateRequest) XXX_Size() int {
	return xxx_messageInfo_ActivitiesHeartRateRequest.Size(m)
}
func (m *ActivitiesHeartRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivitiesHeartRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivitiesHeartRateRequest proto.InternalMessageInfo

func (m *ActivitiesHeartRateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ActivitiesHeartRateRequest) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *ActivitiesHeartRateRequest) GetFitbitToken() *FitbitToken {
	if m != nil {
		return m.FitbitToken
	}
	return nil
}

// Contains list of all Activities Heart Rate tasks
type ActivitiesHeartRateResponse struct {
	// Api version:
	Api  string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Item string `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	// List of all ActivitiesStep tasks
	ActivitiesHeartRate  []*ActivitiesHeartRate `protobuf:"bytes,3,rep,name=activitiesHeartRate,proto3" json:"activitiesHeartRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ActivitiesHeartRateResponse) Reset()         { *m = ActivitiesHeartRateResponse{} }
func (m *ActivitiesHeartRateResponse) String() string { return proto.CompactTextString(m) }
func (*ActivitiesHeartRateResponse) ProtoMessage()    {}
func (*ActivitiesHeartRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{11}
}

func (m *ActivitiesHeartRateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivitiesHeartRateResponse.Unmarshal(m, b)
}
func (m *ActivitiesHeartRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivitiesHeartRateResponse.Marshal(b, m, deterministic)
}
func (m *ActivitiesHeartRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivitiesHeartRateResponse.Merge(m, src)
}
func (m *ActivitiesHeartRateResponse) XXX_Size() int {
	return xxx_messageInfo_ActivitiesHeartRateResponse.Size(m)
}
func (m *ActivitiesHeartRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivitiesHeartRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivitiesHeartRateResponse proto.InternalMessageInfo

func (m *ActivitiesHeartRateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ActivitiesHeartRateResponse) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *ActivitiesHeartRateResponse) GetActivitiesHeartRate() []*ActivitiesHeartRate {
	if m != nil {
		return m.ActivitiesHeartRate
	}
	return nil
}

/////////
type ToDo struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Reminder             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ToDo) Reset()         { *m = ToDo{} }
func (m *ToDo) String() string { return proto.CompactTextString(m) }
func (*ToDo) ProtoMessage()    {}
func (*ToDo) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{12}
}

func (m *ToDo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToDo.Unmarshal(m, b)
}
func (m *ToDo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToDo.Marshal(b, m, deterministic)
}
func (m *ToDo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToDo.Merge(m, src)
}
func (m *ToDo) XXX_Size() int {
	return xxx_messageInfo_ToDo.Size(m)
}
func (m *ToDo) XXX_DiscardUnknown() {
	xxx_messageInfo_ToDo.DiscardUnknown(m)
}

var xxx_messageInfo_ToDo proto.InternalMessageInfo

func (m *ToDo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ToDo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ToDo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ToDo) GetReminder() *timestamp.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

// Create message
type CreateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	ToDo                 *ToDo    `protobuf:"bytes,2,opt,name=toDo,proto3" json:"toDo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{13}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetToDo() *ToDo {
	if m != nil {
		return m.ToDo
	}
	return nil
}

type CreateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{14}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Read message
type ReadRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{15}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	ToDo                 *ToDo    `protobuf:"bytes,2,opt,name=toDo,proto3" json:"toDo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{16}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadResponse) GetToDo() *ToDo {
	if m != nil {
		return m.ToDo
	}
	return nil
}

// Request data to read all todo task
type ReadAllRequest struct {
	// Api version:
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllRequest) Reset()         { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()    {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{17}
}

func (m *ReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllRequest.Unmarshal(m, b)
}
func (m *ReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllRequest.Marshal(b, m, deterministic)
}
func (m *ReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllRequest.Merge(m, src)
}
func (m *ReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAllRequest.Size(m)
}
func (m *ReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllRequest proto.InternalMessageInfo

func (m *ReadAllRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

// Contains list of all todo tasks
type ReadAllResponse struct {
	// Api version:
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// List of all todo tasks
	ToDos                []*ToDo  `protobuf:"bytes,2,rep,name=toDos,proto3" json:"toDos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllResponse) Reset()         { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()    {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b701c7b1c502fe, []int{18}
}

func (m *ReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllResponse.Unmarshal(m, b)
}
func (m *ReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllResponse.Marshal(b, m, deterministic)
}
func (m *ReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllResponse.Merge(m, src)
}
func (m *ReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAllResponse.Size(m)
}
func (m *ReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllResponse proto.InternalMessageInfo

func (m *ReadAllResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadAllResponse) GetToDos() []*ToDo {
	if m != nil {
		return m.ToDos
	}
	return nil
}

func init() {
	proto.RegisterType((*FitbitToken)(nil), "v1.FitbitToken")
	proto.RegisterType((*RefreshTokenRequest)(nil), "v1.RefreshTokenRequest")
	proto.RegisterType((*RefreshTokenResponse)(nil), "v1.RefreshTokenResponse")
	proto.RegisterType((*ActivitiesStep)(nil), "v1.ActivitiesStep")
	proto.RegisterType((*ActivitiesStepRequest)(nil), "v1.ActivitiesStepRequest")
	proto.RegisterType((*ActivitiesStepResponse)(nil), "v1.ActivitiesStepResponse")
	proto.RegisterType((*ActivitiesDistance)(nil), "v1.ActivitiesDistance")
	proto.RegisterType((*ActivitiesDistanceRequest)(nil), "v1.ActivitiesDistanceRequest")
	proto.RegisterType((*ActivitiesDistanceResponse)(nil), "v1.ActivitiesDistanceResponse")
	proto.RegisterType((*ActivitiesHeartRate)(nil), "v1.ActivitiesHeartRate")
	proto.RegisterType((*ActivitiesHeartRateRequest)(nil), "v1.ActivitiesHeartRateRequest")
	proto.RegisterType((*ActivitiesHeartRateResponse)(nil), "v1.ActivitiesHeartRateResponse")
	proto.RegisterType((*ToDo)(nil), "v1.ToDo")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "v1.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "v1.ReadResponse")
	proto.RegisterType((*ReadAllRequest)(nil), "v1.ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "v1.ReadAllResponse")
}

func init() { proto.RegisterFile("todo-service.proto", fileDescriptor_80b701c7b1c502fe) }

var fileDescriptor_80b701c7b1c502fe = []byte{
	// 1027 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xd6, 0xda, 0x4e, 0x9a, 0x1e, 0x27, 0x4e, 0x3a, 0x49, 0x13, 0xc7, 0x0d, 0xe9, 0x32, 0x17,
	0xa5, 0x8a, 0xb0, 0xb7, 0x31, 0xa1, 0x48, 0x05, 0x41, 0xd3, 0x86, 0xaa, 0x95, 0x50, 0x2f, 0xb6,
	0x11, 0xf7, 0x93, 0xdd, 0x13, 0x7b, 0x52, 0x7b, 0x67, 0x99, 0x19, 0x27, 0xad, 0x00, 0x21, 0x81,
	0xc4, 0x05, 0x17, 0x5c, 0xc0, 0x1d, 0xaf, 0xc1, 0x33, 0xf0, 0x00, 0x08, 0xf1, 0x06, 0x3c, 0x08,
	0x9a, 0xd9, 0x59, 0xdb, 0xeb, 0x9f, 0xa8, 0xb9, 0xc8, 0x95, 0x67, 0xce, 0xcf, 0xf7, 0x7d, 0x73,
	0x3c, 0x73, 0xce, 0x02, 0xd1, 0x22, 0x16, 0x4d, 0x85, 0xf2, 0x9c, 0x47, 0xd8, 0x4a, 0xa5, 0xd0,
	0x82, 0x94, 0xce, 0xf7, 0x1b, 0x77, 0x3b, 0x42, 0x74, 0x7a, 0x18, 0x58, 0xcb, 0xc9, 0xe0, 0x34,
	0xd0, 0xbc, 0x8f, 0x4a, 0xb3, 0x7e, 0x9a, 0x05, 0x35, 0x76, 0x5c, 0x00, 0x4b, 0x79, 0xc0, 0x92,
	0x44, 0x68, 0xa6, 0xb9, 0x48, 0x94, 0xf3, 0x7e, 0x68, 0x7f, 0xa2, 0x66, 0x07, 0x93, 0xa6, 0xba,
	0x60, 0x9d, 0x0e, 0xca, 0x40, 0xa4, 0x36, 0x62, 0x3a, 0x9a, 0xfe, 0xe9, 0x41, 0xf5, 0x19, 0xd7,
	0x27, 0x5c, 0x1f, 0x8b, 0xd7, 0x98, 0x90, 0x35, 0x28, 0xb3, 0x94, 0xd7, 0x3d, 0xdf, 0xbb, 0x7f,
	0x33, 0x34, 0x4b, 0xe2, 0x43, 0x95, 0x45, 0x11, 0x2a, 0x65, 0x03, 0xea, 0x25, 0xeb, 0x19, 0x37,
	0x91, 0x1d, 0xb8, 0xa9, 0xcd, 0xe2, 0xf8, 0x6d, 0x8a, 0xf5, 0xb2, 0xf5, 0x8f, 0x0c, 0x84, 0xc2,
	0xb2, 0xc4, 0x53, 0x89, 0xaa, 0x9b, 0x01, 0x54, 0x6c, 0x40, 0xc1, 0x46, 0x36, 0x61, 0x11, 0xdf,
	0xa4, 0x5c, 0xbe, 0xad, 0x2f, 0x58, 0xaf, 0xdb, 0x19, 0xfb, 0x40, 0xa1, 0x7c, 0x11, 0xd7, 0x17,
	0x33, 0x7b, 0xb6, 0xa3, 0x09, 0xac, 0x87, 0x63, 0xf9, 0x21, 0x7e, 0x33, 0x40, 0xa5, 0x67, 0x88,
	0x27, 0x50, 0xe1, 0x1a, 0xfb, 0x4e, 0xb5, 0x5d, 0x93, 0x7d, 0xa8, 0x9e, 0x8e, 0x4e, 0x6c, 0x05,
	0x57, 0xdb, 0xab, 0xad, 0xf3, 0xfd, 0xd6, 0x58, 0x21, 0xc2, 0xf1, 0x18, 0x3a, 0x80, 0x8d, 0x22,
	0x9f, 0x4a, 0x45, 0xa2, 0xf0, 0x1d, 0x09, 0x3f, 0x81, 0xda, 0x18, 0xd8, 0x4b, 0xbc, 0x98, 0xc7,
	0x39, 0x11, 0x46, 0x9f, 0x40, 0xed, 0x30, 0xd2, 0xfc, 0x9c, 0x6b, 0x8e, 0xea, 0x95, 0xc6, 0x94,
	0x34, 0x60, 0x29, 0x66, 0x1a, 0x8f, 0x79, 0x1f, 0x1d, 0xeb, 0x70, 0x4f, 0x36, 0x60, 0x41, 0x69,
	0x4c, 0x95, 0xe3, 0xce, 0x36, 0x34, 0x85, 0xdb, 0x45, 0x8c, 0x6b, 0x2f, 0xd6, 0x77, 0xb0, 0x39,
	0xc9, 0x78, 0xa5, 0x72, 0x7d, 0x06, 0xab, 0xac, 0x90, 0xaf, 0xea, 0x65, 0xbf, 0x7c, 0xbf, 0xda,
	0x26, 0x86, 0x76, 0x02, 0x7a, 0x32, 0x94, 0x7e, 0x05, 0x64, 0x14, 0x72, 0xc4, 0x95, 0x66, 0x49,
	0x84, 0x97, 0xd6, 0xcd, 0xf8, 0x5c, 0x9c, 0xd3, 0x31, 0xdc, 0x53, 0x0d, 0xdb, 0xd3, 0x68, 0xd7,
	0x5e, 0xc1, 0x5f, 0x3c, 0x68, 0xcc, 0xa2, 0xbd, 0x52, 0x19, 0x9f, 0x01, 0x61, 0x53, 0x18, 0xae,
	0x92, 0x9b, 0xc5, 0x4a, 0x0e, 0x19, 0x66, 0x64, 0xd0, 0x2f, 0x61, 0x7d, 0x14, 0xf9, 0x1c, 0x99,
	0xd4, 0x21, 0xd3, 0x97, 0x57, 0x94, 0x40, 0xe5, 0x04, 0x59, 0x9c, 0xcb, 0x31, 0x6b, 0x3a, 0x18,
	0x3f, 0xd2, 0x10, 0xe6, 0xda, 0x4b, 0xf9, 0xab, 0x07, 0x77, 0x66, 0xf2, 0x5e, 0xa9, 0x96, 0x2f,
	0x60, 0x9d, 0x4d, 0x83, 0xb8, 0x62, 0x6e, 0x15, 0x8b, 0x39, 0xe2, 0x98, 0x95, 0x43, 0x7f, 0xf6,
	0xa0, 0x72, 0x2c, 0x8e, 0x04, 0xa9, 0x41, 0x89, 0xc7, 0x96, 0xb8, 0x1c, 0x96, 0x78, 0x6c, 0x9e,
	0xaf, 0xe6, 0xba, 0x97, 0xdf, 0xc1, 0x6c, 0x63, 0xba, 0x6f, 0x8c, 0x2a, 0x92, 0xdc, 0x76, 0x70,
	0xd7, 0x5d, 0xc7, 0x4d, 0xe4, 0x21, 0x2c, 0x49, 0xec, 0xf3, 0x24, 0x46, 0x69, 0x7b, 0x6b, 0xb5,
	0xdd, 0x68, 0x65, 0x03, 0xa2, 0x95, 0x4f, 0x90, 0xd6, 0x71, 0x3e, 0x41, 0xc2, 0x61, 0x2c, 0xfd,
	0x02, 0x56, 0x9e, 0x4a, 0xbc, 0xf4, 0x3f, 0xd8, 0x81, 0x8a, 0x16, 0x47, 0xc2, 0x2a, 0xaa, 0xb6,
	0x97, 0xcc, 0x39, 0x8d, 0xf4, 0xd0, 0x5a, 0x69, 0x1b, 0x6a, 0x39, 0xc0, 0xdc, 0x62, 0x66, 0x87,
	0x2c, 0xe5, 0x87, 0xa4, 0x01, 0x54, 0x43, 0x64, 0xf1, 0x7c, 0xca, 0xc9, 0x84, 0xcf, 0x61, 0x39,
	0x4b, 0x98, 0x4b, 0x71, 0xb9, 0x48, 0x0a, 0x35, 0x93, 0x7f, 0xd8, 0xeb, 0xcd, 0xe5, 0xa4, 0x4f,
	0x61, 0x75, 0x18, 0x33, 0x97, 0x66, 0x17, 0x16, 0x0c, 0xa0, 0xe9, 0xae, 0xe5, 0x02, 0x4f, 0x66,
	0x6e, 0xff, 0xb5, 0x00, 0x55, 0xb3, 0x7f, 0x95, 0xcd, 0x73, 0xd2, 0x33, 0x23, 0x8a, 0xc5, 0x2f,
	0xf1, 0x62, 0x7c, 0x72, 0x10, 0x7b, 0x59, 0x66, 0xcc, 0xae, 0x46, 0x7d, 0xda, 0x91, 0x69, 0xa1,
	0xf4, 0xc7, 0x7f, 0xfe, 0xfb, 0xbd, 0xb4, 0x43, 0xb7, 0x82, 0xf3, 0xfd, 0x20, 0xbb, 0xdb, 0x81,
	0x9b, 0x9e, 0x76, 0xca, 0x3e, 0xf2, 0xf6, 0x88, 0x00, 0x62, 0x8f, 0x50, 0x9c, 0x16, 0xdb, 0x33,
	0x1a, 0xa6, 0xa3, 0x6b, 0xcc, 0x72, 0xcd, 0x22, 0x1c, 0xdd, 0xe1, 0xc0, 0x0c, 0x94, 0x80, 0xf5,
	0x7a, 0x86, 0xf0, 0x07, 0xd8, 0x2c, 0x12, 0x0e, 0x5b, 0xed, 0x7b, 0x73, 0x7a, 0x8b, 0x23, 0xde,
	0x9d, 0xe7, 0x76, 0xe4, 0xf7, 0x2c, 0xb9, 0x4f, 0xef, 0x4c, 0x90, 0xe7, 0x2d, 0x39, 0x17, 0xf0,
	0x93, 0x07, 0x5b, 0x45, 0x05, 0xa3, 0xde, 0xb4, 0x3b, 0xef, 0x45, 0x3a, 0x0d, 0x77, 0xe7, 0xfa,
	0x9d, 0x88, 0x0f, 0xac, 0x88, 0xf7, 0xe9, 0xce, 0x84, 0x88, 0xae, 0x89, 0x94, 0x4c, 0x0f, 0x55,
	0x3c, 0x87, 0x1b, 0xee, 0xea, 0x10, 0x92, 0xfd, 0x81, 0xe3, 0x77, 0xad, 0xb1, 0x5e, 0xb0, 0x39,
	0xf0, 0x0d, 0x0b, 0x5e, 0x23, 0xcb, 0x06, 0xdc, 0x7c, 0x03, 0x1a, 0x30, 0x72, 0x04, 0x8b, 0xd9,
	0x6b, 0x22, 0xb7, 0x4c, 0x52, 0xe1, 0x69, 0x36, 0xc8, 0xb8, 0xc9, 0xc1, 0xac, 0x5b, 0x98, 0x15,
	0xba, 0x94, 0xc3, 0x18, 0x3d, 0x8f, 0xa1, 0x62, 0xe8, 0xc8, 0x6a, 0x4e, 0x9c, 0x23, 0xac, 0x8d,
	0x0c, 0x2e, 0xff, 0xb6, 0xcd, 0x5f, 0x25, 0x2b, 0x43, 0x19, 0xdf, 0xf2, 0xf8, 0xfb, 0x27, 0xff,
	0x7a, 0xbf, 0x1d, 0xfe, 0xed, 0x91, 0xd7, 0xb0, 0x6c, 0x6e, 0xb3, 0xef, 0x3e, 0x4f, 0xe9, 0xd7,
	0x70, 0xaf, 0x23, 0x9a, 0x1d, 0x99, 0x46, 0xcd, 0xae, 0xd6, 0x69, 0x53, 0xa2, 0xd2, 0xcd, 0x3e,
	0x46, 0x52, 0xb8, 0x08, 0x3f, 0x95, 0xe2, 0x0c, 0x23, 0x4d, 0x6e, 0x19, 0xbf, 0x0a, 0x82, 0x0e,
	0xd7, 0xdd, 0xc1, 0x49, 0x2b, 0x12, 0xfd, 0xc6, 0xf6, 0x19, 0x53, 0x22, 0x89, 0xba, 0x03, 0x96,
	0x74, 0x3e, 0x7e, 0xf8, 0xb8, 0x2b, 0x74, 0x9f, 0xf1, 0x9e, 0x71, 0xb5, 0xcb, 0xfb, 0xad, 0x07,
	0x7b, 0x9e, 0xd7, 0x5e, 0x63, 0x69, 0xda, 0xe3, 0x91, 0xfd, 0x36, 0x0d, 0xce, 0x94, 0x48, 0x1e,
	0x4d, 0x59, 0xc2, 0x4f, 0xa1, 0x7c, 0xf0, 0xe0, 0x80, 0x1c, 0xc0, 0x5e, 0x88, 0x7a, 0x20, 0x13,
	0x8c, 0xfd, 0x8b, 0x2e, 0x26, 0xbe, 0xee, 0xa2, 0x2f, 0x51, 0x89, 0x81, 0x8c, 0xd0, 0x8f, 0x05,
	0x2a, 0x3f, 0x11, 0xda, 0xc7, 0x37, 0x5c, 0xe9, 0x16, 0x59, 0x84, 0xca, 0x1f, 0x25, 0xef, 0xc6,
	0xc9, 0xa2, 0x6d, 0x86, 0x1f, 0xfd, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x30, 0x82, 0x49, 0xa7, 0x76,
	0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ToDoServiceClient is the client API for ToDoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ToDoServiceClient interface {
	// Get New Refresh Token
	ReadNewRefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	// Read All ActivitiesStepResponse tasks
	ReadActivitiesStep(ctx context.Context, in *ActivitiesStepRequest, opts ...grpc.CallOption) (*ActivitiesStepResponse, error)
	// Read All ActivitiesDistanceResponse tasks
	ReadActivitiesDistance(ctx context.Context, in *ActivitiesDistanceRequest, opts ...grpc.CallOption) (*ActivitiesDistanceResponse, error)
	// Read All ActivitiesHeartRateResponse tasks
	ReadActivitiesHeartRate(ctx context.Context, in *ActivitiesHeartRateRequest, opts ...grpc.CallOption) (*ActivitiesHeartRateResponse, error)
	// Read all todo tasks
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error)
	// Create new todo task
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// Read todo todo task
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
}

type toDoServiceClient struct {
	cc *grpc.ClientConn
}

func NewToDoServiceClient(cc *grpc.ClientConn) ToDoServiceClient {
	return &toDoServiceClient{cc}
}

func (c *toDoServiceClient) ReadNewRefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/v1.ToDoService/ReadNewRefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) ReadActivitiesStep(ctx context.Context, in *ActivitiesStepRequest, opts ...grpc.CallOption) (*ActivitiesStepResponse, error) {
	out := new(ActivitiesStepResponse)
	err := c.cc.Invoke(ctx, "/v1.ToDoService/ReadActivitiesStep", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) ReadActivitiesDistance(ctx context.Context, in *ActivitiesDistanceRequest, opts ...grpc.CallOption) (*ActivitiesDistanceResponse, error) {
	out := new(ActivitiesDistanceResponse)
	err := c.cc.Invoke(ctx, "/v1.ToDoService/ReadActivitiesDistance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) ReadActivitiesHeartRate(ctx context.Context, in *ActivitiesHeartRateRequest, opts ...grpc.CallOption) (*ActivitiesHeartRateResponse, error) {
	out := new(ActivitiesHeartRateResponse)
	err := c.cc.Invoke(ctx, "/v1.ToDoService/ReadActivitiesHeartRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error) {
	out := new(ReadAllResponse)
	err := c.cc.Invoke(ctx, "/v1.ToDoService/ReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/v1.ToDoService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/v1.ToDoService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToDoServiceServer is the server API for ToDoService service.
type ToDoServiceServer interface {
	// Get New Refresh Token
	ReadNewRefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	// Read All ActivitiesStepResponse tasks
	ReadActivitiesStep(context.Context, *ActivitiesStepRequest) (*ActivitiesStepResponse, error)
	// Read All ActivitiesDistanceResponse tasks
	ReadActivitiesDistance(context.Context, *ActivitiesDistanceRequest) (*ActivitiesDistanceResponse, error)
	// Read All ActivitiesHeartRateResponse tasks
	ReadActivitiesHeartRate(context.Context, *ActivitiesHeartRateRequest) (*ActivitiesHeartRateResponse, error)
	// Read all todo tasks
	ReadAll(context.Context, *ReadAllRequest) (*ReadAllResponse, error)
	// Create new todo task
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// Read todo todo task
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
}

func RegisterToDoServiceServer(s *grpc.Server, srv ToDoServiceServer) {
	s.RegisterService(&_ToDoService_serviceDesc, srv)
}

func _ToDoService_ReadNewRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).ReadNewRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/ReadNewRefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).ReadNewRefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_ReadActivitiesStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivitiesStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).ReadActivitiesStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/ReadActivitiesStep",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).ReadActivitiesStep(ctx, req.(*ActivitiesStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_ReadActivitiesDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivitiesDistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).ReadActivitiesDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/ReadActivitiesDistance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).ReadActivitiesDistance(ctx, req.(*ActivitiesDistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_ReadActivitiesHeartRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivitiesHeartRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).ReadActivitiesHeartRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/ReadActivitiesHeartRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).ReadActivitiesHeartRate(ctx, req.(*ActivitiesHeartRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).ReadAll(ctx, req.(*ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToDoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ToDoService",
	HandlerType: (*ToDoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadNewRefreshToken",
			Handler:    _ToDoService_ReadNewRefreshToken_Handler,
		},
		{
			MethodName: "ReadActivitiesStep",
			Handler:    _ToDoService_ReadActivitiesStep_Handler,
		},
		{
			MethodName: "ReadActivitiesDistance",
			Handler:    _ToDoService_ReadActivitiesDistance_Handler,
		},
		{
			MethodName: "ReadActivitiesHeartRate",
			Handler:    _ToDoService_ReadActivitiesHeartRate_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _ToDoService_ReadAll_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ToDoService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ToDoService_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo-service.proto",
}
